ppo:
  n_iterations: 200
  val_period: 100
  n_epochs: 1
  minibatch_size: 2
  horizon: 40
  epsilon: 0.2
  use_gae: false
  gae_lambda: 0.95

discount_rate: 0.95
diff_reward: false
baseline_lr: 0.0005
entropy_weight: 0
batch_size: 2
reward_scale: 1.0
#lr: 0.010
lr: 0.0016134816080499328
decay: 0.0008404361781997002
optimizer: Adam

eval:
  n_routes: 15
  min_route_len: 11
  max_route_len: 42

dataset:
  type: mumford
  kwargs:
    path: datasets/mumford_dataset/Instances
    city: Gozo

defaults:
  - _self_
  - experiment: standard
  - model: bestsofar_feb2023
