ppo:
  n_iterations: 400
  val_period: 10
  n_epochs: 1
  minibatch_size: 512
  horizon: 32
  epsilon: 0.2
  gamma: 0.99
  use_gae: true
  gae_lambda: 0.95

entropy_weight: 0.0
batch_size: 512
reward_scale: 1.0
lr: 0.0016134816080499328
decay: 0.0008404361781997002
optimizer: Adam

eval:
  min_route_len: 2
  max_route_len: 12
  n_routes: 10

dataset:
  type: pickle
  kwargs:
    path: datasets/mixed_50
    space_scale: 0.6
    demand_scale: 0.2

defaults:
  - _self_
  - experiment: standard
  - model: bestsofar_feb2023
